name: 🤖 Auto Merge

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

permissions:
  pull-requests: write
  contents: read
  checks: read

jobs:
  enable-auto-merge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
